include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:

linter:
  rules:
    avoid_annotating_with_dynamic: false
    avoid_function_literals_in_foreach_calls: false
    no_logic_in_create_state: false
    avoid_types_on_closure_parameters: false
